# Generated by Django 3.2.11 on 2022-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValuation',
            fields=[
                ('id_company_valuation', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('company_code', models.CharField(max_length=2)),
                ('sim_round', models.IntegerField()),
                ('sim_step', models.IntegerField()),
                ('sim_calendar_date', models.DateTimeField()),
                ('sim_period', models.IntegerField()),
                ('sim_elapsed_steps', models.IntegerField()),
                ('bank_cash_account', models.FloatField()),
                ('accounts_receivable', models.IntegerField()),
                ('bank_loan', models.FloatField()),
                ('accounts_payable', models.FloatField()),
                ('profit', models.FloatField()),
                ('debt_loading', models.FloatField()),
                ('credit_rating', models.CharField(max_length=10)),
                ('company_risk_rate_pct', models.FloatField()),
                ('company_valuation', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'company_valuation',
                'managed': False,
            },
        ),
    ]
