# Generated by Django 3.2.11 on 2022-05-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpsim_helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyvaluation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pricingconditions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={},
        ),
    ]
