# Generated by Django 4.0.3 on 2022-03-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpsim_helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_running',
            field=models.BooleanField(default=False, verbose_name='Partie en cours'),
        ),
    ]
