# Generated by Django 3.2.11 on 2022-05-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erpsim_helper', '0002_auto_20220523_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvaluation',
            name='id_game',
            field=models.ForeignKey(db_column='id_game', null=True, on_delete=django.db.models.deletion.CASCADE, to='erpsim_helper.game'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='id_game',
            field=models.ForeignKey(db_column='id_game', null=True, on_delete=django.db.models.deletion.CASCADE, to='erpsim_helper.game'),
        ),
        migrations.AddField(
            model_name='pricingconditions',
            name='id_game',
            field=models.ForeignKey(db_column='id_game', null=True, on_delete=django.db.models.deletion.CASCADE, to='erpsim_helper.game'),
        ),
        migrations.AddField(
            model_name='sales',
            name='id_game',
            field=models.ForeignKey(db_column='id_game', null=True, on_delete=django.db.models.deletion.CASCADE, to='erpsim_helper.game'),
        ),
    ]
