# Generated by Django 4.0.4 on 2022-05-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpsim_helper', '0004_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValuation',
            fields=[
                ('id_company_valuation', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('company_code', models.CharField(max_length=2)),
                ('sim_round', models.IntegerField()),
                ('sim_step', models.IntegerField()),
                ('sim_calendar_date', models.DateTimeField()),
                ('sim_period', models.IntegerField()),
                ('sim_elapsed_steps', models.IntegerField()),
                ('bank_cash_account', models.FloatField()),
                ('accounts_receivable', models.IntegerField()),
                ('bank_loan', models.FloatField()),
                ('accounts_payable', models.FloatField()),
                ('profit', models.FloatField()),
                ('debt_loading', models.FloatField()),
                ('credit_rating', models.CharField(max_length=10)),
                ('company_risk_rate_pct', models.FloatField()),
                ('company_valuation', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'company_valuation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameNumber', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=2)),
                ('date_time', models.DateTimeField()),
                ('sentence', models.CharField(max_length=300)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
