# Generated by Django 4.0.4 on 2022-05-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpsim_helper', '0005_companyvaluation_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=2)),
                ('date_time', models.DateTimeField()),
                ('element', models.CharField(max_length=300)),
                ('sentence', models.CharField(max_length=300)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
