# Generated by Django 4.0.3 on 2022-03-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='gameNumber',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='login',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='password',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
    ]
